#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix

git clone --single-branch -b master https://github.com/ian-r-rose/dask-labextension.git
cd dask-labextension
jlpm install   # Install npm package dependencies
jlpm run build  # Compile the TypeScript sources to Javascript
jupyter labextension install  # Install the current directory as an extension

pip install -e .
jupyter serverextension enable --sys-prefix dask_labextension

#EOF
